// Generated by gencpp from file frontier_exploration/GetNextFrontier.msg
// DO NOT EDIT!


#ifndef FRONTIER_EXPLORATION_MESSAGE_GETNEXTFRONTIER_H
#define FRONTIER_EXPLORATION_MESSAGE_GETNEXTFRONTIER_H

#include <ros/service_traits.h>


#include <frontier_exploration/GetNextFrontierRequest.h>
#include <frontier_exploration/GetNextFrontierResponse.h>


namespace frontier_exploration
{

struct GetNextFrontier
{

typedef GetNextFrontierRequest Request;
typedef GetNextFrontierResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNextFrontier
} // namespace frontier_exploration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::frontier_exploration::GetNextFrontier > {
  static const char* value()
  {
    return "4204bbb25df206dc841362c99d2c39cb";
  }

  static const char* value(const ::frontier_exploration::GetNextFrontier&) { return value(); }
};

template<>
struct DataType< ::frontier_exploration::GetNextFrontier > {
  static const char* value()
  {
    return "frontier_exploration/GetNextFrontier";
  }

  static const char* value(const ::frontier_exploration::GetNextFrontier&) { return value(); }
};


// service_traits::MD5Sum< ::frontier_exploration::GetNextFrontierRequest> should match 
// service_traits::MD5Sum< ::frontier_exploration::GetNextFrontier > 
template<>
struct MD5Sum< ::frontier_exploration::GetNextFrontierRequest>
{
  static const char* value()
  {
    return MD5Sum< ::frontier_exploration::GetNextFrontier >::value();
  }
  static const char* value(const ::frontier_exploration::GetNextFrontierRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::frontier_exploration::GetNextFrontierRequest> should match 
// service_traits::DataType< ::frontier_exploration::GetNextFrontier > 
template<>
struct DataType< ::frontier_exploration::GetNextFrontierRequest>
{
  static const char* value()
  {
    return DataType< ::frontier_exploration::GetNextFrontier >::value();
  }
  static const char* value(const ::frontier_exploration::GetNextFrontierRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::frontier_exploration::GetNextFrontierResponse> should match 
// service_traits::MD5Sum< ::frontier_exploration::GetNextFrontier > 
template<>
struct MD5Sum< ::frontier_exploration::GetNextFrontierResponse>
{
  static const char* value()
  {
    return MD5Sum< ::frontier_exploration::GetNextFrontier >::value();
  }
  static const char* value(const ::frontier_exploration::GetNextFrontierResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::frontier_exploration::GetNextFrontierResponse> should match 
// service_traits::DataType< ::frontier_exploration::GetNextFrontier > 
template<>
struct DataType< ::frontier_exploration::GetNextFrontierResponse>
{
  static const char* value()
  {
    return DataType< ::frontier_exploration::GetNextFrontier >::value();
  }
  static const char* value(const ::frontier_exploration::GetNextFrontierResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRONTIER_EXPLORATION_MESSAGE_GETNEXTFRONTIER_H
