// Generated by gencpp from file frontier_exploration/UpdateBoundaryPolygon.msg
// DO NOT EDIT!


#ifndef FRONTIER_EXPLORATION_MESSAGE_UPDATEBOUNDARYPOLYGON_H
#define FRONTIER_EXPLORATION_MESSAGE_UPDATEBOUNDARYPOLYGON_H

#include <ros/service_traits.h>


#include <frontier_exploration/UpdateBoundaryPolygonRequest.h>
#include <frontier_exploration/UpdateBoundaryPolygonResponse.h>


namespace frontier_exploration
{

struct UpdateBoundaryPolygon
{

typedef UpdateBoundaryPolygonRequest Request;
typedef UpdateBoundaryPolygonResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateBoundaryPolygon
} // namespace frontier_exploration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::frontier_exploration::UpdateBoundaryPolygon > {
  static const char* value()
  {
    return "fcd73e86a17cffec115813ce5a863c84";
  }

  static const char* value(const ::frontier_exploration::UpdateBoundaryPolygon&) { return value(); }
};

template<>
struct DataType< ::frontier_exploration::UpdateBoundaryPolygon > {
  static const char* value()
  {
    return "frontier_exploration/UpdateBoundaryPolygon";
  }

  static const char* value(const ::frontier_exploration::UpdateBoundaryPolygon&) { return value(); }
};


// service_traits::MD5Sum< ::frontier_exploration::UpdateBoundaryPolygonRequest> should match 
// service_traits::MD5Sum< ::frontier_exploration::UpdateBoundaryPolygon > 
template<>
struct MD5Sum< ::frontier_exploration::UpdateBoundaryPolygonRequest>
{
  static const char* value()
  {
    return MD5Sum< ::frontier_exploration::UpdateBoundaryPolygon >::value();
  }
  static const char* value(const ::frontier_exploration::UpdateBoundaryPolygonRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::frontier_exploration::UpdateBoundaryPolygonRequest> should match 
// service_traits::DataType< ::frontier_exploration::UpdateBoundaryPolygon > 
template<>
struct DataType< ::frontier_exploration::UpdateBoundaryPolygonRequest>
{
  static const char* value()
  {
    return DataType< ::frontier_exploration::UpdateBoundaryPolygon >::value();
  }
  static const char* value(const ::frontier_exploration::UpdateBoundaryPolygonRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::frontier_exploration::UpdateBoundaryPolygonResponse> should match 
// service_traits::MD5Sum< ::frontier_exploration::UpdateBoundaryPolygon > 
template<>
struct MD5Sum< ::frontier_exploration::UpdateBoundaryPolygonResponse>
{
  static const char* value()
  {
    return MD5Sum< ::frontier_exploration::UpdateBoundaryPolygon >::value();
  }
  static const char* value(const ::frontier_exploration::UpdateBoundaryPolygonResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::frontier_exploration::UpdateBoundaryPolygonResponse> should match 
// service_traits::DataType< ::frontier_exploration::UpdateBoundaryPolygon > 
template<>
struct DataType< ::frontier_exploration::UpdateBoundaryPolygonResponse>
{
  static const char* value()
  {
    return DataType< ::frontier_exploration::UpdateBoundaryPolygon >::value();
  }
  static const char* value(const ::frontier_exploration::UpdateBoundaryPolygonResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRONTIER_EXPLORATION_MESSAGE_UPDATEBOUNDARYPOLYGON_H
